#!/bin/bash

echo "🔐 VERIFICAÇÃO DE SECRETS NECESSÁRIOS PARA PIPELINE GOL DE OURO"
echo "=============================================================="
echo ""

echo "📋 SECRETS OBRIGATÓRIOS PARA FUNCIONAMENTO COMPLETO:"
echo ""

echo "1️⃣ FLY_API_TOKEN"
echo "   Descrição: Token de autenticação Fly.io"
echo "   Como obter: flyctl auth token"
echo "   Comando: gh secret set FLY_API_TOKEN -b \"seu_token_aqui\""
echo ""

echo "2️⃣ VERCEL_TOKEN"
echo "   Descrição: Token de autenticação Vercel"
echo "   Como obter: vercel login && vercel whoami"
echo "   Comando: gh secret set VERCEL_TOKEN -b \"seu_token_aqui\""
echo ""

echo "3️⃣ VERCEL_ORG_ID"
echo "   Descrição: ID da organização Vercel"
echo "   Como obter: vercel orgs list"
echo "   Comando: gh secret set VERCEL_ORG_ID -b \"seu_org_id\""
echo ""

echo "4️⃣ VERCEL_PROJECT_ID"
echo "   Descrição: ID do projeto Vercel"
echo "   Como obter: vercel projects list"
echo "   Comando: gh secret set VERCEL_PROJECT_ID -b \"seu_project_id\""
echo ""

echo "5️⃣ SUPABASE_URL (Opcional)"
echo "   Descrição: URL do projeto Supabase"
echo "   Como obter: Painel Supabase → Settings → API"
echo "   Comando: gh secret set SUPABASE_URL -b \"https://seuprojeto.supabase.co\""
echo ""

echo "6️⃣ SUPABASE_KEY (Opcional)"
echo "   Descrição: Chave anônima do Supabase"
echo "   Como obter: Painel Supabase → Settings → API"
echo "   Comando: gh secret set SUPABASE_KEY -b \"sua_chave_anonima\""
echo ""

echo "7️⃣ SLACK_WEBHOOK_URL (Opcional)"
echo "   Descrição: Webhook do Slack para alertas"
echo "   Como obter: Slack → Apps → Incoming Webhooks"
echo "   Comando: gh secret set SLACK_WEBHOOK_URL -b \"https://hooks.slack.com/...\""
echo ""

echo "8️⃣ DISCORD_WEBHOOK_URL (Opcional)"
echo "   Descrição: Webhook do Discord para alertas"
echo "   Como obter: Discord → Server Settings → Integrations → Webhooks"
echo "   Comando: gh secret set DISCORD_WEBHOOK_URL -b \"https://discord.com/api/webhooks/...\""
echo ""

echo "🚀 INSTRUÇÕES DE CONFIGURAÇÃO:"
echo "=============================="
echo ""
echo "1. Instale o GitHub CLI:"
echo "   Windows: winget install GitHub.cli"
echo "   macOS: brew install gh"
echo "   Linux: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
echo ""
echo "2. Faça login no GitHub:"
echo "   gh auth login"
echo ""
echo "3. Configure os secrets usando os comandos acima"
echo ""
echo "4. Verifique os secrets configurados:"
echo "   gh secret list"
echo ""

echo "✅ STATUS ATUAL:"
echo "================"
echo "❌ GitHub CLI não instalado - Configure manualmente via GitHub Web UI"
echo "📋 Acesse: https://github.com/indesconectavel/gol-de-ouro/settings/secrets/actions"
echo "🔧 Adicione os secrets listados acima"
