# fly.toml para Gol de Ouro Backend v1.1.1 - PRODUÇÃO
app = "goldeouro-backend"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile.production"
  ignorefile = ".dockerignore"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    soft_limit = 100
    hard_limit = 200

  [[services.http_checks]]
    path = "/health"
    interval = "15s"
    timeout = "5s"
    method = "get"

# Configurações de escalabilidade
[deploy]
  release_command = "echo 'Deploying Gol de Ouro Backend v1.1.1'"
  strategy = "rolling"

# Configurações de recursos
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
